import React, { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, Save } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

type Entry = { id: string; text: string; createdAt: string };
export const JournalView: React.FC = () => {
  const { t } = useLanguage();
  const [entries, setEntries] = useState<Entry[]>([]); const [text, setText] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/journal').then(r => r.ok ? r.json() : { entries: [] }).then(data => setEntries(data.entries)).catch(() => undefined); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch('/api/journal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setEntries(current => [data.entry, ...current]); setText(''); } catch (err: any) { setError(err.message || 'Could not save your entry.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-3xl space-y-6 pb-10">
    <section className="relative overflow-hidden rounded-[30px] border border-white/15 bg-[#151518] p-7 sm:p-9"><div className="rah-grain pointer-events-none absolute inset-0" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-orange-300">{t('journal.badge')} · private space</p><h2 className="mt-2 font-kanit text-4xl font-black uppercase tracking-[-.04em] text-white">{t('journal.title')}</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-300">{t('journal.subtitle')}</p></div><BookOpen className="absolute bottom-5 right-6 h-20 w-20 text-white/5" /></section>
    <form onSubmit={save} className="rounded-[26px] border border-white/10 bg-[#151518] p-5 sm:p-7"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/45">One prompt</p><h3 className="mt-1 text-xl font-bold text-white">{t('journal.prompt')}</h3></div><span className="text-[10px] font-semibold text-white/45">{text.length}/2000</span></div><textarea required maxLength={2000} value={text} onChange={e => setText(e.target.value)} className="min-h-40 w-full rounded-2xl border border-white/10 bg-white/[.035] p-4 text-sm leading-relaxed text-white outline-none focus:border-fuchsia-400" placeholder={t('journal.placeholder')} />{error && <p className="mt-3 text-xs font-semibold text-rose-300">{error}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-600 via-purple-600 to-orange-500 px-5 py-3 text-xs font-bold uppercase tracking-wider text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? t('journal.saving') : t('journal.save')} <ArrowRight className="h-4 w-4" /></button></form>
    <section className="rounded-[26px] border border-white/10 bg-[#151518] p-5 sm:p-7"><div className="mb-4 flex items-center gap-2 border-b border-white/10 pb-4"><CalendarDays className="h-4 w-4 text-fuchsia-300" /><h3 className="text-lg font-bold text-white">{t('journal.history')}</h3></div>{entries.length ? <div className="space-y-3">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-sm leading-relaxed text-slate-200">{entry.text}</p><p className="mt-3 text-[10px] font-bold uppercase tracking-wider text-white/40">{new Date(entry.createdAt).toLocaleString()}</p></article>)}</div> : <p className="rounded-2xl border border-dashed border-white/15 p-5 text-sm text-slate-400">{t('journal.empty')}</p>}</section>
  </div>;
};
