import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ur';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Rah.',
    'app.tagline': 'Find Your Ikigai Without Losing Your Mind',
    'app.subtitle': 'Pop-Art Career Reasoning Engine • Grounded in Pakistan Pathways',
    'header.framework': 'The Rah Framework',
    'modal.title': 'The Ikigai Framework in Rah',
    'modal.desc': 'Ikigai (生きがい) represents your reason for being — the precise overlap of four foundational life vectors:',
    'modal.love': '1. Love:',
    'modal.love.desc': 'Core passions, game dev, design, trading & favorite subjects.',
    'modal.goodAt': '2. Good At:',
    'modal.goodAt.desc': 'Natural logic, skills, avatar archetype, and strengths.',
    'modal.worldNeeds': '3. World Needs:',
    'modal.worldNeeds.desc': 'Value created for Pakistan society and global markets.',
    'modal.paidFor': '4. Paid For:',
    'modal.paidFor.desc': 'Concrete university entrance tests (NUST NET, FAST NU, MDCAT) & degrees.',
    'modal.grounding': 'Pakistani Grounding:',
    'modal.grounding.desc': 'Maps directly to MDCAT, ECAT, NUST NET, KMU-CAT, FAST NU, IBA Karachi, and local public/private university options.',
    'modal.close': 'Close Explanation',
    'hero.badge': '💥 Pop-Art Ikigai Discovery for Pakistani Students 💥',
    'hero.title': 'Find Your Ikigai Without Losing Your Mind',
    'hero.desc': 'Diagnose your student avatar, build your interest sandbox, budget your test runway (3, 6, or 12 months), and unlock concrete study resources for Pakistani universities.',
    'footer.title': 'Rah. (راه)',
    'footer.tag': '• Find Your Ikigai Without Losing Your Mind',
    'footer.powered': 'Powered by Gemini AI Studio • Grounded in Pakistan Entrance Exams & Degrees',
    'quiz.samples': '⚡ Preset Student Avatars',
    'quiz.autofill': '1-click load',
    'quiz.autofill.desc': 'Pick a comic profile to auto-diagnose an avatar & pop-art roadmap:',
    'onboarding.step1': 'Step 1: Personality & Vibe Check',
    'onboarding.step1.desc': 'Diagnose your learning archetype through 5 quick comic scenarios.',
    'onboarding.step2': 'Step 2: Custom Interest Sandbox',
    'onboarding.step2.desc': 'Click or type custom badges for what you actually love.',
    'onboarding.step3': 'Step 3: The Runway & Time Budgeter',
    'onboarding.step3.desc': 'Set your exact preparation timeline for realistic workload calculations.',
    'quiz.step1': 'Step 1: Current Academic Track & Location',
    'quiz.track': 'Academic Track (FSc / A-Level / ICS / I.Com)',
    'quiz.city': 'City / Location in Pakistan',
    'quiz.step2': 'Step 2: Interest Sandbox & Custom Mix',
    'quiz.step3': 'Step 3: Strengths & Skills',
    'quiz.step4': 'Step 4: Pakistan & World Impact',
    'quiz.step5': 'Step 5: Budget & Runway Selection',
    'quiz.submit': 'BOOM! Synthesize My Ikigai & Roadmap',
    'quiz.submitting': 'ZAP! Synthesizing Rah Ikigai & Roadmap...',
    'results.analysisComplete': 'Analysis Complete',
    'results.heading': 'Student Ikigai & Academic Pathway Synthesis',
    'results.copy': 'Copy Output',
    'results.copied': 'Copied',
    'results.json': 'JSON Schema',
    'results.hideJson': 'Hide JSON',
    'results.newSearch': 'New Search',
    'results.yourProfile': 'Your Ikigai Profile',
    'results.recommendedPathways': 'Recommended Career & Degree Pathways',
    'results.alternativePaths': 'Alternative & Adjacent Pathways You Might Not Have Considered',
    'results.alternativeSubtitle': 'Based on your ikigai profile and strengths, here are related disciplines that offer unique opportunities:',
    'results.whyRelevant': 'Why it connects to your Ikigai:',
    'results.transferableSkills': 'Transferable Skills:',
    'results.exampleDegrees': 'Degrees in Pakistan:',
    'results.topInstitutions': 'Top Universities:',
    'results.roadmap': 'Runway Roadmap & Progress Tracker',
    'results.progress': 'Progress:',
    'results.clearProgress': 'Reset Checkboxes',
    'results.markAll': 'Mark All Complete',
    'results.ikigaiSummaryTitle': 'AI-Generated Ikigai Profile Summary',
    'results.ikigaiSummarySubtitle': 'AI synthesis of your core motivations, discovered strengths, and value intersection:',
    'results.coreMotivations': 'Core Motivations & Driving Passions',
    'results.discoveredStrengths': 'Discovered Strengths & Core Traits',
    'results.valueIntersection': 'Ikigai Value Intersection',
    'results.whatYouLove': 'What You Love',
    'results.whatYoureGoodAt': 'What You Are Good At',
    'results.whatWorldNeeds': 'What Pakistan Needs',
    'results.whatPaysWell': 'Market Value & Target Track',
    'results.radarChartTitle': 'Competency Radar & Growth Gaps',
    'results.radarChartSubtitle': 'Spider-web analysis comparing your current strengths against target university & career benchmarks:',
    'results.currentStrength': 'Your Current Level',
    'results.targetLevel': 'Roadmap Target Level',
    'results.growthAreasHeading': 'Key Areas for Growth & Action:',
    'results.scholarshipsTitle': 'Pakistani Scholarships & Financial Aid',
    'results.scholarshipsSubtitle': 'Google Search Grounded opportunities tailored to your career path and location:',
    'results.searchScholarshipsBtn': 'Search Live Google Grounded Scholarships',
    'results.searchingScholarships': 'Searching Live Google Index...',
    'results.scholarshipProvider': 'Provider:',
    'results.scholarshipCoverage': 'Coverage:',
    'results.scholarshipEligibility': 'Eligibility:',
    'results.scholarshipDeadline': 'Application Cycle:',
    'results.groundedSources': 'Grounded Sources from Google Search:',
    'results.resources': 'Recommended Study Resources & Guides',
    'results.note': 'Note: This profile is a starting point for exploration, not a definitive diagnosis of your potential. Your autonomy is central to the path you choose.',
    'reminder.title': 'Daily Study Nudge & Roadmap Reminder',
    'reminder.subtitle': 'Schedule a daily browser or in-app reminder to maintain your university prep momentum:',
    'reminder.enable': 'Enable Daily Nudge',
    'reminder.disable': 'Nudge Disabled',
    'reminder.timeLabel': 'Scheduled Reminder Time:',
    'reminder.quickPresets': 'Quick Time Presets:',
    'reminder.morning': '08:00 AM',
    'reminder.afternoon': '02:00 PM',
    'reminder.evening': '07:00 PM',
    'reminder.night': '10:00 PM',
    'reminder.testBtn': 'Test Nudge Now 🔔',
    'reminder.permissionBtn': 'Allow Browser Notifications',
    'reminder.permissionGranted': 'Browser Alerts Enabled',
    'reminder.permissionDenied': 'In-App Alerts Active',
    'reminder.activeMsg': 'Daily reminder scheduled for',
    'reminder.nudgeToastTitle': '🚀 Daily Study Roadmap Nudge!',
    'reminder.nudgeToastBody': 'Time to check off today\'s university preparation milestones. Maintain your momentum!',
    'register.title': 'Register Yourself',
    'register.subtitle': 'Create your official student profile to unlock personalized university pathways & test roadmaps.',
    'register.fullName': 'Full Name',
    'register.email': 'Email Address',
    'register.phone': 'Phone / WhatsApp',
    'register.city': 'City / Location in Pakistan',
    'register.stage': 'Academic Stage / Track',
    'register.goal': 'Target Degree Goal',
    'register.avatar': 'Choose Your Student Avatar',
    'register.bio': 'Short Student Ambition / Bio',
    'register.passcode': 'Security Passcode',
    'register.submit': 'Complete Student Registration 🚀',
    'register.success': 'Profile Registered Successfully!',
    'register.alreadyRegistered': 'Registered Student Profile',
    'register.editProfile': 'Edit Profile Details',
    'register.newRegister': 'Register Another Student',
    'register.continueQuiz': 'Proceed to Ikigai Career Diagnostic 🎯',
    'auth.login': 'Login', 'auth.logout': 'Logout', 'auth.journey': 'Journey', 'auth.journal': 'Journal',
    'auth.registerBadge': 'Student Portal Registration', 'auth.welcomeBack': 'Welcome back',
    'auth.loginSubtitle': 'Sign in to access your student profile.', 'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Your password', 'auth.signingIn': 'Signing in…', 'auth.signIn': 'Sign in',
    'auth.newHere': 'New here?', 'auth.createAccount': 'Create an account', 'auth.registered': 'Registered',
    'auth.active': 'Registered Active', 'auth.autofill': 'Autofill Sample Student', 'auth.cancelEdit': 'Cancel Editing',
    'auth.saved': 'Welcome, {name}! Your account has been created successfully.'
    , 'journey.badge': 'Purpose studio', 'journey.greeting': 'Hi {name}, build a future that fits you.'
    , 'journey.description': 'Your guided journey turns self-reflection into an actionable academic and career direction for Pakistan.'
    , 'journey.continue': 'Continue your discovery', 'journey.steps': 'Know yourself|Complete the personality and strengths reflection|Reflect daily|Notice what gives you energy and meaning|Discover careers|Explore Pakistan-focused study and career routes|Build your roadmap|Turn your best-fit direction into practical milestones|Find your Ikigai|See the connection between passion, skill, impact, and work'
    , 'journal.badge': 'Daily reflection', 'journal.title': 'Capture what gave you energy today.'
    , 'journal.subtitle': 'A few honest notes build better career suggestions over time.', 'journal.prompt': 'What did you enjoy, learn, or find difficult today?'
    , 'journal.placeholder': 'For example: I enjoyed explaining a physics concept to a classmate…', 'journal.save': 'Save reflection', 'journal.saving': 'Saving…', 'journal.history': 'Your reflection history', 'journal.empty': 'Your first reflection will appear here.'
  },
  ur: {
    'app.title': 'راہ.',
    'app.tagline': 'اپنا اکیگائی دریافت کریں — بغیر ذہنی پریشانی کے',
    'app.subtitle': 'پاپ آرٹ کیریئر ریزننگ انجن • پاکستان کے تعلیمی راستوں پر مبنی',
    'header.framework': 'راہ کا فریم ورک',
    'modal.title': 'راہ میں اکیگائی (Ikigai) فریم ورک',
    'modal.desc': 'اکیگائی (生きがい) زندگی کا مقصد اور توازن پیش کرتا ہے — یہ چار بنیادی اصولوں کا حسین امتزاج ہے:',
    'modal.love': '1. پسندیدہ (Love):',
    'modal.love.desc': 'آپ کے پسندیدہ مضامین، کوڈنگ، ڈیزائن، اور دلچسپیاں۔',
    'modal.goodAt': '2. مہارت (Good At):',
    'modal.goodAt.desc': 'آپ کی قدرتی صلاحیتیں اور مہارتیں۔',
    'modal.worldNeeds': '3. دنیا کی ضرورت (World Needs):',
    'modal.worldNeeds.desc': 'پاکستان اور معاشرے کے لیے آپ کی خدمات۔',
    'modal.paidFor': '4. روزگار اور آمدن (Paid For):',
    'modal.paidFor.desc': 'یونیورسٹی ڈگری اور انٹری ٹیسٹ کے راستے۔',
    'modal.grounding': 'پاکستان کی بنیاد:',
    'modal.grounding.desc': 'MDCAT، ECAT، NUST NET، KMU-CAT، FAST NU، اور مقامی یونیورسٹیوں کے مواقع سے براہ راست منسلک۔',
    'modal.close': 'بند کریں',
    'hero.badge': '💥 پاکستانی طلباء کے لیے پاپ آرٹ اکیگائی گائیڈ 💥',
    'hero.title': 'اپنا اکیگائی دریافت کریں — بغیر کسی ذہنی دباؤ کے',
    'hero.desc': 'اپنا اسٹوڈنٹ اوتار منتخب کریں، دلچسپیوں کا بکس بنائیں، 3، 6 یا 12 ماہ کا وقت مقرر کریں اور پاکستان کی یونیورسٹیوں کی مکمل تیاری کے ذرائع دیکھیں۔',
    'footer.title': 'راہ (Rah)',
    'footer.tag': '• اپنا اکیگائی دریافت کریں',
    'footer.powered': 'جمنائی اے آئی کے ذریعے • پاکستانی یونیورسٹیوں اور ٹیسٹوں پر مبنی',
    'quiz.samples': '⚡ نمونہ اسٹوڈنٹ اوتار',
    'quiz.autofill': 'ایک کلک سے بھریں',
    'quiz.autofill.desc': 'کومک پروفائل منتخب کر کے فوری اپنا روڈ میپ دیکھیں:',
    'onboarding.step1': 'مرحلہ 1: پرسنالٹی اور وائب چیک',
    'onboarding.step1.desc': '5 مختصر سوالات کے ذریعے اپنا سیکھنے کا اوتار پہچانیں۔',
    'onboarding.step2': 'مرحلہ 2: کسٹم انٹرسٹ سینڈ بکس',
    'onboarding.step2.desc': 'اپنی پسند کی دلچسپیاں ٹیگ کریں یا کسٹم لکھیں۔',
    'onboarding.step3': 'مرحلہ 3: تیاری کی ٹائم لائن اور بجٹ',
    'onboarding.step3.desc': '3، 6 یا 12 ماہ کا ٹائم فریم چنیں۔',
    'quiz.step1': 'مرحلہ 1: موجودہ تعلیمی شعبہ اور شہر',
    'quiz.track': 'تعلیمی شعبہ (FSc / A-Level / Matric / O-Level)',
    'quiz.city': 'پاکستان میں شہر / مقام',
    'quiz.step2': 'مرحلہ 2: آپ کو کیا پسند ہے (دلچسپیاں)',
    'quiz.step3': 'مرحلہ 3: آپ کی صلاحیتیں (مہارتیں)',
    'quiz.step4': 'مرحلہ 4: پاکستان اور دنیا کی ضرورت',
    'quiz.step5': 'مرحلہ 5: تیاری کی ٹائم لائن اور بجٹ',
    'quiz.submit': 'BOOM! میرا اکیگائی اور روڈ میپ بنائیں',
    'quiz.submitting': 'ZAP! اکیگائی اور روڈ میپ کی تیاری جاری ہے...',
    'results.analysisComplete': 'تجزیہ مکمل',
    'results.heading': 'طالب علم کا اکیگائی اور تعلیمی روڈ میپ',
    'results.copy': 'کاپی کریں',
    'results.copied': 'کاپی ہو گیا',
    'results.json': 'JSON اسکیمہ',
    'results.hideJson': 'JSON چھپائیں',
    'results.newSearch': 'نیا تلاش',
    'results.yourProfile': 'آپ کا اکیگائی پروفائل',
    'results.recommendedPathways': 'تجویز کردہ تعلیمی راستے',
    'results.alternativePaths': 'متبادل اور متعلقہ تعلیمی شعبے',
    'results.alternativeSubtitle': 'آپ کے اکیگائی پروفائل اور مہارتوں پر مبنی دیگر متعلقہ شعبے:',
    'results.whyRelevant': 'آپ کے اکیگائی سے مطابقت:',
    'results.transferableSkills': 'منتقلی کے قابل مہارتیں:',
    'results.exampleDegrees': 'پاکستان میں ڈگریاں:',
    'results.topInstitutions': 'بہترین یونیورسٹیاں:',
    'results.roadmap': 'روڈ میپ اور پیشرفت',
    'results.progress': 'پیشرفت:',
    'results.clearProgress': 'چیک باکسز دوبارہ ترتیب دیں',
    'results.markAll': 'تمام مکمل کریں',
    'results.ikigaiSummaryTitle': 'AI ایکی گائی پروفائل کا خلاصہ',
    'results.ikigaiSummarySubtitle': 'آپ کی بنیادی ترغیبات، صلاحیتوں اور پاکستانی مارکیٹ میں موقع کی مصنوعی ذہانت سے تجزیہ کردہ جھلک:',
    'results.coreMotivations': 'بنیادی ترغیبات اور جذبہ',
    'results.discoveredStrengths': 'دریافت شدہ صلاحیتیں اور خوبیاں',
    'results.valueIntersection': 'ایکی گائی کا مرکز',
    'results.whatYouLove': 'آپ کا جذبہ',
    'results.whatYoureGoodAt': 'آپ کی ماہرانہ صلاحیت',
    'results.whatWorldNeeds': 'پاکستان کی ضرورت',
    'results.whatPaysWell': 'ترجیحی مالی ہدف',
    'results.radarChartTitle': 'صلاحیتوں کا اسپائیڈر چارٹ (کمپیٹنسی ریڈار)',
    'results.radarChartSubtitle': 'آپ کی موجودہ صلاحیتوں اور یونیورسٹی ڈگری کی ضروریات کا موازنہ:',
    'results.currentStrength': 'آپ کی موجودہ سطح',
    'results.targetLevel': 'روڈ میپ کا ہدف',
    'results.growthAreasHeading': 'ترقی اور بہتری کے اہم شعبے:',
    'results.scholarshipsTitle': 'پاکستان میں اسکالرشپ اور مالی امداد',
    'results.scholarshipsSubtitle': 'گوگل سرچ پر مبنی اسکالرشپس اور گرانٹس کی معلومات:',
    'results.searchScholarshipsBtn': 'گوگل لائیو سرچ سے اسکالرشپ تلاش کریں',
    'results.searchingScholarships': 'گوگل انڈیکس میں اسکالرشپس تلاش کی جا رہی ہیں...',
    'results.scholarshipProvider': 'ادارہ:',
    'results.scholarshipCoverage': 'مالی امداد کا حجم:',
    'results.scholarshipEligibility': 'اہلیت کے ضوابط:',
    'results.scholarshipDeadline': 'درخواست کی تاریخ/دورانیہ:',
    'results.groundedSources': 'گوگل سرچ سے براہ راست مصدقہ لنکس:',
    'results.resources': 'تجویز کردہ مطالعہ کے ذرائع',
    'results.note': 'نوٹ: یہ پروفائل تلاش کا شروعاتی نقطہ ہے، کوئی حتمی فیصلہ نہیں۔ آپ کا انتخاب ہمیشہ آزادانہ ہے۔',
    'reminder.title': 'روزانہ مطالعہ کی یاد دہانی (اسٹڈی نڈج)',
    'reminder.subtitle': 'اپنی تعلیم اور روڈ میپ کی پیشرفت کا جائزہ لینے کے لیے روزانہ کا وقت مقرر کریں:',
    'reminder.enable': 'روزانہ کی یاد دہانی آن کریں',
    'reminder.disable': 'یاد دہانی بند ہے',
    'reminder.timeLabel': 'یاد دہانی کا وقت:',
    'reminder.quickPresets': 'فوری انتخاب:',
    'reminder.morning': 'صبح 08:00',
    'reminder.afternoon': 'دوپہر 02:00',
    'reminder.evening': 'شام 07:00',
    'reminder.night': 'رات 10:00',
    'reminder.testBtn': 'ٹیسٹ الرٹ بجائیں 🔔',
    'reminder.permissionBtn': 'براؤزر نوٹیفکیشن کی اجازت دیں',
    'reminder.permissionGranted': 'براؤزر نوٹیفکیشن آن ہے',
    'reminder.permissionDenied': 'ان ایپ پاپ اپ فعال ہے',
    'reminder.activeMsg': 'روزانہ مطالعہ کی یاد دہانی کا وقت:',
    'reminder.nudgeToastTitle': '🚀 روزانہ تعلیمی روڈ میپ کا جائزہ لیں!',
    'reminder.nudgeToastBody': 'آج کے انٹری ٹیسٹ اور یونیورسٹی تیاری کے مقاصد مکمل کرنے کا وقت آ گیا ہے۔',
    'register.title': 'خود کو درج کریں (رجسٹریشن)',
    'register.subtitle': 'تعلیمی ڈگریوں اور روڈ میپ کی تخصیص کے لیے اپنا طالب علم پروفائل درج کریں۔',
    'register.fullName': 'مکمل نام',
    'register.email': 'ای میل ایڈریس',
    'register.phone': 'فون / واٹس ایپ نمبر',
    'register.city': 'پاکستان میں شہر / مقام',
    'register.stage': 'موجودہ تعلیمی شعبہ',
    'register.goal': 'ترجیحی ڈگری کا ہدف',
    'register.avatar': 'اپنا اسٹوڈنٹ اوتار منتخب کریں',
    'register.bio': 'تعلیمی مقصد / مختصر تعارف',
    'register.passcode': 'سیکیورٹی پاس کوڈ',
    'register.submit': 'پروفائل محفوظ اور درج کریں 🚀',
    'register.success': 'پروفائل کامیابی سے رجسٹر ہو گیا!',
    'register.alreadyRegistered': 'رجسٹرڈ طالب علم کا پروفائل',
    'register.editProfile': 'پروفائل کی تفصیلات تبدیل کریں',
    'register.newRegister': 'نیا اکاؤنٹ رجسٹر کریں',
    'register.continueQuiz': 'اکیگائی کیریئر روڈ میپ کی طرف بڑھیں 🎯',
    'auth.login': 'لاگ اِن', 'auth.logout': 'لاگ آؤٹ', 'auth.journey': 'میرا سفر', 'auth.journal': 'ڈائری',
    'auth.registerBadge': 'طالب علم پورٹل رجسٹریشن', 'auth.welcomeBack': 'خوش آمدید',
    'auth.loginSubtitle': 'اپنے طالب علم پروفائل تک رسائی کے لیے لاگ اِن کریں۔', 'auth.password': 'پاس ورڈ',
    'auth.passwordPlaceholder': 'اپنا پاس ورڈ درج کریں', 'auth.signingIn': 'لاگ اِن ہو رہا ہے…', 'auth.signIn': 'لاگ اِن کریں',
    'auth.newHere': 'نئے صارف ہیں؟', 'auth.createAccount': 'اکاؤنٹ بنائیں', 'auth.registered': 'رجسٹرڈ',
    'auth.active': 'فعال رجسٹریشن', 'auth.autofill': 'نمونہ طالب علم خودکار بھریں', 'auth.cancelEdit': 'ترمیم منسوخ کریں',
    'auth.saved': 'خوش آمدید، {name}! آپ کا اکاؤنٹ کامیابی سے بن گیا ہے۔'
    , 'journey.badge': 'مقصد کا سفر', 'journey.greeting': 'خوش آمدید {name}، ایسا مستقبل بنائیں جو آپ کے لیے موزوں ہو۔'
    , 'journey.description': 'یہ رہنمائی پر مبنی سفر خود شناسی کو پاکستان کے لیے عملی تعلیمی اور کیریئر سمت میں بدلتا ہے۔'
    , 'journey.continue': 'اپنی دریافت جاری رکھیں', 'journey.steps': 'خود کو جانیں|شخصیت اور صلاحیتوں کا جائزہ مکمل کریں|روزانہ غور و فکر|جانیں کہ آپ کو کیا توانائی اور خوشی دیتا ہے|کیریئر دریافت کریں|پاکستان میں موزوں تعلیم اور کیریئر کے راستے دیکھیں|اپنا روڈ میپ بنائیں|اپنی بہترین سمت کو عملی مراحل میں تبدیل کریں|اپنا اکیگائی دریافت کریں|شوق، صلاحیت، اثر اور کام کا تعلق دیکھیں'
    , 'journal.badge': 'روزانہ غور و فکر', 'journal.title': 'آج جس چیز نے آپ کو توانائی دی، اسے لکھیں۔'
    , 'journal.subtitle': 'کچھ ایماندارانہ نوٹس وقت کے ساتھ بہتر کیریئر تجاویز بناتے ہیں۔', 'journal.prompt': 'آج آپ نے کس چیز سے لطف اٹھایا، کیا سیکھا، یا کیا مشکل محسوس کیا؟'
    , 'journal.placeholder': 'مثال: مجھے اپنے ساتھی کو فزکس کا تصور سمجھانا پسند آیا…', 'journal.save': 'غور و فکر محفوظ کریں', 'journal.saving': 'محفوظ کیا جا رہا ہے…', 'journal.history': 'آپ کی تحریروں کی تاریخ', 'journal.empty': 'آپ کی پہلی تحریر یہاں نظر آئے گی۔'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>('en');

  const toggleLang = () => {
    setLang(prev => (prev === 'en' ? 'ur' : 'en'));
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      <div dir={lang === 'ur' ? 'rtl' : 'ltr'} className={lang === 'ur' ? 'font-sans' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
